version: "3.9"
services:
  postgresdb:
    build:
      context: .
      dockerfile: docker/postgres.dockerfile
    container_name: postgresdb
    restart: unless-stopped
    ports:
      - 5432:5432
  expensetracker:
    depends_on:
      - postgresdb
    build:
      context: .
      dockerfile: docker/expensetracker.dockerfile
    container_name: expensetracker
    environment:
      - spring_profiles_active=docker
    restart: on-failure
    ports:
      - 8081:8080
    stdin_open: true
    tty: true
